// <auto-generated />
using System;
using Aeronave.Infraestructure.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aeronave.Infraestructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20220729225906_initial-create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aeronave.Domain.Model.Aeronaves.AeronaveModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Aeropuerto")
                        .HasColumnType("integer")
                        .HasColumnName("aeropuerto");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<int>("CapacidadTanque")
                        .HasColumnType("integer")
                        .HasColumnName("capacidadTanque");

                    b.Property<int>("EstadoAeronave")
                        .HasColumnType("integer")
                        .HasColumnName("estadoAeronave");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<int>("NroAsientos")
                        .HasColumnType("integer")
                        .HasColumnName("nroAsientos");

                    b.HasKey("Id");

                    b.ToTable("Aeronave", (string)null);
                });

            modelBuilder.Entity("Aeronave.Domain.Model.Vuelos.Vuelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AeronaveId")
                        .HasColumnType("uuid")
                        .HasColumnName("aeronaveId");

                    b.Property<int>("AeropuertoDestino")
                        .HasColumnType("integer")
                        .HasColumnName("aeropuertoDestino");

                    b.Property<int>("AeropuertoOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("aeropuertoOrigen");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horaLlegada");

                    b.Property<DateTime>("HoraPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horaPartida");

                    b.Property<int>("IdTripulacion")
                        .HasColumnType("integer")
                        .HasColumnName("idTripulacion");

                    b.Property<string>("NroVuelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nroVuelo");

                    b.HasKey("Id");

                    b.ToTable("Vuelo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
