// <auto-generated />
using System;
using Aeronave.Infraestructure.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aeronave.Infraestructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Aeronave.Domain.Model.Aeronaves.AeronaveModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aeropuerto")
                        .HasColumnType("int")
                        .HasColumnName("aeropuerto");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<int>("CapacidadTanque")
                        .HasColumnType("int")
                        .HasColumnName("capacidadTanque");

                    b.Property<int>("EstadoAeronave")
                        .HasColumnType("int")
                        .HasColumnName("estadoAeronave");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.Property<int>("NroAsientos")
                        .HasColumnType("int")
                        .HasColumnName("nroAsientos");

                    b.HasKey("Id");

                    b.ToTable("Aeronave", (string)null);
                });

            modelBuilder.Entity("Aeronave.Domain.Model.Aeronaves.Vuelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AeronaveId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("aeronaveId");

                    b.Property<int>("AeropuertoDestino")
                        .HasColumnType("int")
                        .HasColumnName("aeropuertoDestino");

                    b.Property<int>("AeropuertoOrigen")
                        .HasColumnType("int")
                        .HasColumnName("aeropuertoOrigen");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("datetime2")
                        .HasColumnName("horaLlegada");

                    b.Property<DateTime>("HoraPartida")
                        .HasColumnType("datetime2")
                        .HasColumnName("horaPartida");

                    b.Property<int>("IdTripulacion")
                        .HasColumnType("int")
                        .HasColumnName("idTripulacion");

                    b.Property<string>("NroVuelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nroVuelo");

                    b.HasKey("Id");

                    b.ToTable("Vuelo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
