name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: aeronaveapi
  IMAGE_TAG: ${{ github.run_number }}
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    -
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag noglory/aeronaveapi:1.${{ env.IMAGE_TAG }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Push to DockerHub
      run: docker push noglory/aeronaveapi:1.${{ env.IMAGE_TAG }}
  staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.SSH_HOST }}
          user: root
          key: ${{ secrets.SSH_KEY}}
