name: Staging deployment

on:
  push:
    branches: [main]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dotnet app
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
          script: |
            mkdir test
            cd test
            git clone git@github.com:EuchiMano/AirplaneMs.git
            echo 'Deployment successful to digital ocean'
